import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LANGUAGES = ["hi", "te", "ta", "kn", "ml", "mr", "bn", "gu", "pa"];

const newStrings = {
  "auth": {
    "welcomeBack": "Welcome Back!",
    "loginDesc": "Login to continue your celebration journey",
    "google": "Continue with Google",
    "or": "or",
    "emailLogin": "Email Login",
    "otpLogin": "Mobile OTP Login",
    "noAccount": "Don't have an account?",
    "signUp": "Sign up",
    "emailLabel": "Email Address",
    "passwordLabel": "Password",
    "rememberMe": "Remember me",
    "forgotPassword": "Forgot Password?",
    "signIn": "Login",
    "signingIn": "Signing in...",
    "termsAndPrivacy": "By logging in, you agree to our Terms of Service and Privacy Policy.",
    "mobileLabel": "Mobile Number",
    "otpLabel": "ENTER 4-DIGIT OTP",
    "otpSent": "OTP sent to",
    "resendIn": "Resend in {{timer}}s",
    "resendOtp": "Resend OTP",
    "sendOtp": "Send OTP",
    "sending": "Sending",
    "verifyOtp": "Verify OTP",
    "verified": "Verified",
    "welcomeBackRedirect": "Welcome back to VIBENESTS. Redirecting you...",
    "registerTitle": "Create Account",
    "registerDesc": "Join VibeNests and start your celebration journey",
    "orRegisterEmail": "or register with email",
    "fullName": "Full Name",
    "phoneNumber": "Phone Number",
    "city": "City",
    "selectCity": "Select your city",
    "agreeTerms": "I agree to the Terms of Service and Privacy Policy",
    "createAccount": "Create My Account",
    "haveAccount": "Already have an account?",
    "signInLink": "Sign In",
    "successTitle": "Account Created!",
    "successDesc": "Welcome to VibeNests, {{name}}. Your luxury journey begins now.",
    "continueLogin": "Continue to Login",
    "adminPortal": "Admin Portal",
    "adminRegisterTitle": "Register Admin",
    "adminRegisterDesc": "Create a secure administrative account for VibeNests",
    "officialEmail": "Official Email",
    "adminUsername": "Admin Username",
    "accessCode": "Admin Access Code",
    "role": "Admin Role",
    "selectRole": "Select role",
    "agreeAdminTerms": "I agree to the Admin Terms of Service and Privacy Policy. This account will be reviewed before activation.",
    "registerBtn": "Register Admin Account",
    "alreadyAdmin": "Already have an admin account?",
    "adminLoginLink": "Admin Login",
    "adminSuccessTitle": "Admin Registered!",
    "adminSuccessDesc": "Welcome, {{name}}. Your account is pending verification.",
    "assignedRole": "Assigned Role",
    "goLogin": "Go to Admin Login",
    "resetTitle": "Set Your Password",
    "resetDesc": "Create a secure password to activate your VibeNests account.",
    "newPassword": "New Password",
    "reqLength": "At least 8 characters",
    "reqUpper": "One uppercase letter",
    "reqNumber": "One number",
    "reqMatch": "Passwords match",
    "setBtn": "Set Password & Activate Account",
    "resetSuccessTitle": "Password Set!",
    "resetSuccessDesc": "Your account is now active. Redirecting to login..."
  },
  "hero": {
    "feat_perfectOccasion": "Perfect Occasion",
    "feat_luxuryAmbience": "luxury Ambience",
    "feat_privateSecure": "Private secure",
    "feat_support247": "Support 24/7"
  },
  "userDashboard": {
    "welcome": "Welcome back",
    "goldMember": "Gold Member",
    "logout": "Logout",
    "cancel": "Cancel",
    "totalBookings": "Total Bookings",
    "activeWallet": "Active Wallet",
    "reviewsWritten": "Reviews Written",
    "quickActions": "Quick Actions",
    "bookNewSuite": "Book New Suite",
    "specialOffers": "Special Offers",
    "needHelp": "Need Help?",
    "recentActivity": "Recent Activity",
    "upcomingStays": "Upcoming Stays",
    "completedStays": "Completed Stays",
    "noBookings": "No bookings found.",
    "walletBalance": "Wallet Balance",
    "paymentHistory": "Payment History",
    "addMoney": "Add Money",
    "refundStatus": "Refund Status",
    "transactionId": "Transaction ID",
    "date": "Date",
    "amount": "Amount",
    "status": "Status",
    "profileSettings": "Profile Settings",
    "saveChanges": "Save Changes",
    "weCanHelp": "We Can Help With",
    "contactUs": "Contact Us",
    "supportHours": "Support Hours",
    "emailSupport": "Email Support",
    "supportNumber": "Support Number",
    "writeReview": "Write a Review",
    "shareExperience": "Share Your Experience",
    "overallExperience": "Overall Experience",
    "categoryRatings": "Category Ratings",
    "yourReview": "Your Review",
    "submitReview": "Submit Review",
    "bookingDetails": "Booking Details",
    "dashboard": "Dashboard",
    "browseSuites": "Browse Suites",
    "myBookings": "My Bookings",
    "upcomingBookings": "Upcoming Bookings",
    "pastBookings": "Past Bookings",
    "walletPayments": "Payments",
    "celebrationMembership": "Celebration Membership",
    "specialOffersReferrals": "Special Offers",
    "helpSupport": "Help & Support",
    "makeEvery": "Make Every",
    "momentMemorable": "Moment Memorable",
    "heroDesc": "Handpicked private suites with premium amenities for your special celebrations.",
    "bookYourSuite": "Book Your Suite",
    "loyaltyPoints": "Loyalty Points",
    "nightsStayed": "Nights Stayed",
    "totalSpent": "Total Spent",
    "explore": "Explore",
    "available": "Available",
    "comingSoon": "Coming Soon",
    "availableSuites": "Available Suites",
    "upcomingSuites": "Upcoming Suites",
    "newBooking": "New Booking",
    "newBookingDesc": "Explore & reserve suites",
    "modifyBooking": "Modify Booking",
    "modifyBookingDesc": "Change dates or room type",
    "contactConcierge": "Contact Concierge",
    "contactConciergeDesc": "24/7 personal assistance",
    "raiseRequest": "Raise a Request",
    "raiseRequestDesc": "Report issues or requests",
    "conciergeTitle": "Concierge",
    "conciergeDesc": "24/7 dedicated personal assistance for every need",
    "fineDiningTitle": "Fine Dining",
    "fineDiningDesc": "Reserve exclusive in-suite and restaurant dining",
    "spaWellnessTitle": "Spa & Wellness",
    "spaWellnessDesc": "Book rejuvenating spa treatments and wellness",
    "location": "Location",
    "duration": "Duration",
    "checkIn": "Check-in",
    "checkOut": "Check-out",
    "selectedAddons": "Selected Add-ons",
    "noAddons": "No add-ons selected.",
    "paymentDetails": "Payment Details",
    "method": "Method",
    "totalPaid": "Total Paid",
    "bookingTimeline": "Booking Timeline",
    "invoice": "Invoice",
    "invoiceDesc": "Invoice #{{id}}-INV · Generated on booking confirmation",
    "downloadInvoicePdf": "Download Invoice PDF",
    "cancellationRefund": "Cancellation & Refund",
    "requestCancellation": "Request Cancellation",
    "viewDetails": "View Details",
    "joinNow": "Join Now",
    "capacity": "Capacity",
    "priceNight": "Price / night",
    "bookNow": "Book Now",
    "guests": "guests",
    "guestsCount": "{{count}} guests",
    "downloadInvoice": "Download Invoice",
    "status_completed": "Completed",
    "status_pending": "Pending",
    "status_failed": "Failed",
    "browseSuitesDesc": "Explore and book from our luxury suite collection",
    "countAvailable": "{{count}} Available",
    "searchPlaceholder": "Search suites or occasions...",
    "filterAll": "All",
    "filterActive": "Active",
    "filterInactive": "Inactive",
    "noSuitesFound": "No suites found.",
    "bookingsCount": "{{count}} bookings",
    "fromDate": "From",
    "toDate": "To",
    "status_all": "All",
    "status_confirmed": "Confirmed",
    "status_cancelled": "Cancelled",
    "clear": "Clear",
    "loadingBookings": "Loading bookings...",
    "noBookingsMatch": "No bookings match the selected filters.",
    "premiumMember": "Premium Member",
    "availableBalance": "Available Balance",
    "walletCreditsRefunds": "Wallet credits & refunds",
    "withdraw": "Withdraw",
    "loyaltyPointsDesc": "Earn 1 pt = ₹10 spent",
    "redeemPoints": "Redeem Points",
    "transactions": "Transactions",
    "importStatement": "Import Statement",
    "paymentMethods": "Payment Methods",
    "refunds": "Refunds",
    "paymentAnalytics": "Payment Analytics",
    "totalCredits": "Total Credits",
    "totalDebits": "Total Debits",
    "netFlow": "Net Flow",
    "savedPaymentMethods": "Saved Payment Methods",
    "addNew": "Add New",
    "default": "DEFAULT",
    "edit": "Edit",
    "delete": "Delete",
    "setDefault": "Default",
    "recentTransactions": "Recent Transactions",
    "import": "Import",
    "searchPlaceholderShort": "Search...",
    "filterCredits": "Credits",
    "filterDebits": "Debits",
    "noTransactionsFound": "No transactions found.",
    "packagesCount": "{{count}} Packages",
    "clearAll": "Clear All",
    "maxPrice": "Max Price",
    "comparingCount": "Comparing ({{count}}/3)",
    "compareNow": "Compare Now",
    "noPackagesMatch": "No packages match your filters.",
    "clearFilters": "Clear filters",
    "compare": "+ Compare",
    "compared": "✓ Compare",
    "whatsIncluded": "What's Included",
    "bookThisPackage": "Book This Package",
    "close": "Close",
    "occasion_all": "All",
    "occasion_birthday": "Birthday",
    "occasion_anniversary": "Anniversary",
    "occasion_proposal": "Proposal",
    "occasion_baby_shower": "Baby Shower",
    "occasion_corporate_events": "Corporate Events",
    "occasion_other_celebrations": "Other Celebrations",
    "sort_popularity": "Popularity",
    "sort_price_low_to_high": "Price: Low to High",
    "sort_price_high_to_low": "Price: High to Low",
    "sort_most_booked": "Most Booked",
    "badge_most_popular": "Most Popular",
    "badge_best_for_couples": "Best for Couples",
    "badge_perfect_surprise": "Perfect Surprise",
    "badge_great_for_parties": "Great for Parties",
    "tabOffers": "Offers",
    "tabReferrals": "Referrals",
    "tabCoupons": "Coupons",
    "validUntil": "Valid until {{date}}",
    "yourReferralCode": "Your Referral Code",
    "referralDesc": "Share this code and earn ₹500 for every friend who books",
    "copied": "Copied!",
    "copyCode": "Copy Code",
    "share": "Share",
    "friendsReferred": "Friends Referred",
    "successfulBookings": "Successful Bookings",
    "rewardsEarned": "Rewards Earned",
    "howItWorks": "How It Works",
    "refStep1": "Share your unique referral code with friends",
    "refStep2": "Friend signs up and makes their first booking",
    "refStep3": "You earn ₹500 wallet credit instantly",
    "refStep4": "Your friend gets ₹250 off their first stay",
    "applyCoupon": "Apply a Coupon",
    "couponPlaceholder": "Enter coupon code...",
    "apply": "Apply",
    "couponApplied": "Coupon {{code}} applied successfully!",
    "couponInvalid": "Invalid or expired coupon code.",
    "availableCoupons": "Available Coupons",
    "minSpend": "Min. spend: {{amount}}",
    "copy": "Copy",
    "offerTitle_0": "Early Bird Discount",
    "offerTitle_1": "Extended Stay Benefit",
    "offerTitle_2": "Weekday Escape",
    "offerTitle_3": "Anniversary Package",
    "offerDesc_0": "Book 60 days in advance and save 20% on select suites.",
    "offerDesc_1": "Stay 5 nights or more and enjoy your 6th night complimentary.",
    "offerDesc_2": "Exclusive rates on Monday–Thursday bookings across all properties.",
    "offerDesc_3": "Complimentary suite upgrade and floral decor for anniversary stays.",
    "offerBadge_0": "20% OFF",
    "offerBadge_1": "FREE NIGHT",
    "offerBadge_2": "15% OFF",
    "offerBadge_3": "EXCLUSIVE",
    "fullName": "Full Name",
    "dob": "Date of Birth",
    "helpTopic1": "Booking queries & confirmations",
    "helpTopic2": "Celebration package customisation",
    "helpTopic3": "Payment & refund requests",
    "helpTopic4": "Live celebration sharing support",
    "helpTopic5": "Complaints & escalations",
    "helpTopic6": "Legal & privacy matters",
    "emailSupportDesc": "We respond within 1–2 business days",
    "supportNumberDesc": "Call or WhatsApp during support hours",
    "supportHoursValue": "9:00 AM – 9:00 PM IST",
    "supportHoursDesc": "Monday to Sunday, incl. public holidays",
    "helpSupportDesc": "Vibenests Private Luxury Suites — we're here every day",
    "supportHoursBadge": "9 AM – 9 PM IST",
    "businessInfoTitle": "Vibenests Private Luxury Suites",
    "businessInfoDesc": "Premium private suite bookings and celebration experiences. Our team is available 7 days a week to assist you.",
    "privacyPolicy": "Privacy Policy",
    "termsOfUse": "Terms of Use",
    "weAreHereToHelp": "We're Here to Help",
    "privateLuxurySuitesAvailableEveryDay": "Private Luxury Suites — available every day",
    "eventConfirmedPaid": "Booking confirmed & paid",
    "eventCheckInReminder": "Check-in reminder sent",
    "eventRefundedToWallet": "Deposit refunded to wallet",
    "eventCancelledByGuest": "Booking cancelled by guest",
    "eventCancellationProcessed": "Cancellation processed",
    "policyCompleted": "Booking completed – cancellation not applicable.",
    "policyJan21": "Free cancellation until {{date1}}. 50% refund between {{date1}}–{{date2}}. No refund after {{date2}}.",
    "policyMar03": "Free cancellation until {{date1}}. 30% refund after that. No refund within 48 hrs.",
    "policyCancelled2Days": "Cancelled 2 days before check-in. 25% refund applied per policy.",
    "txnDescBookingPayment": "Booking Payment – {{suite}} {{id}}",
    "txnDescWalletTopUp": "Wallet Top-up via UPI",
    "txnDescRefund": "Refund – Cancelled Booking {{id}}",
    "txnDescAdvancePayment": "Advance Payment – {{suite}} {{id}}",
    "txnDescWalletWithdrawal": "Wallet Withdrawal to Bank",
    "creditCard": "Credit Card",
    "debitCard": "Debit Card",
    "wallet": "Wallet",
    "bank": "Bank",
    "fullContactPage": "Full Contact Page",
    "thankYou": "Thank You!",
    "reviewSubmittedDesc": "Your review has been submitted. It helps us craft better experiences for every guest.",
    "backToDashboard": "Back to Dashboard",
    "home": "Home",
    "writeReviewDesc": "Your honest feedback helps us deliver exceptional luxury experiences for every guest.",
    "bookingConfirmed": "Booking Confirmed!",
    "bookingConfirmedDesc": "Your luxury suite has been reserved and payment received. A confirmation email has been sent to you.",
    "bookingId": "Booking ID: #VN{{id}}",
    "paidInFull": "Paid in Full",
    "advancePaid": "Advance Paid (20%)",
    "balancePayableAtVenue": "Balance ₹{{amount}} payable at venue",
    "viewMyBookings": "View My Bookings",
    "secureBooking": "Secure booking",
    "suiteBooking": "Suite Booking",
    "premiumExperience": "Premium experience",
    "bookLuxurySuiteSteps": "Book a luxury suite in six effortless steps",
    "guestsBaseRate": "{{minCap}}–{{maxCap}} guests · {{price}} base rate",
    "yourJourney": "Your Journey",
    "progress": "Progress",
    "stepText": "Step {{step}}",
    "selectOccasion": "Select Occasion",
    "chooseDateTime": "Choose Date & Time",
    "addonsCustomizations": "Add-ons & Customizations",
    "bookingSummary": "Booking Summary",
    "payment": "Payment",
    "selectDate": "Select Date",
    "selectTimeSlot": "Select Time Slot",
    "slotDuration": "2h 30m per slot",
    "selectedSlot": "Selected: {{start}} – {{end}}",
    "durationShort": "· 2 hrs 30 mins",
    "priceBase": "base",
    "numberOfPersons": "Number of Persons",
    "personsLimitDesc": "Min {{min}} · Max {{max}} · ₹{{rate}}/extra person above min",
    "personsLimitDescNoExtra": "Min {{min}} · Max {{max}}",
    "selectSuiteFirst": "Select a suite first",
    "guestsLimitText": "{{count}} / {{max}} guests",
    "specialRequests": "Special Requests",
    "specialRequestsPlaceholder": "Add any special instructions...",
    "yourCelebration": "Your Celebration",
    "noOccasion": "No occasion",
    "noDate": "No date",
    "noTime": "No time",
    "suite": "Suite",
    "capacityGuests": "Capacity: {{min}}–{{max}} guests",
    "noSuiteSelected": "No suite selected.",
    "addons": "Add-ons",
    "personsExtraRate": "{{count}} persons ({{extra}} extra × ₹{{rate}})",
    "paymentOptions": "Payment Options",
    "payNow": "Pay Now",
    "payNowDesc": "Pay the full amount ₹{{total}} and confirm instantly.",
    "payAtVenue": "Pay at Venue",
    "payAtVenueDesc": "Pay 20% advance ₹{{advance}} now. Balance ₹{{balance}} at venue.",
    "amountToPayNow": "Amount to Pay Now",
    "advanceToPayNow": "Advance to Pay Now (20%)",
    "cardsUpiNetBanking": "Cards / UPI / Net Banking",
    "securedByRazorpay": "Secured by Razorpay",
    "processing": "Processing...",
    "proceedToPay": "Proceed to Pay ₹{{amount}}",
    "razorpayEncryption": "Powered by Razorpay · 256-bit SSL encryption",
    "validationError": "Please complete the required selection before continuing.",
    "back": "Back",
    "continue": "Continue",
    "backToSummary": "Back to Summary",
    "brandSub": "Private Luxury Suites",
    "nights": "Nights",
    "paymentMethod": "Payment Method",
    "category": "Category",
    "occasion_birthday_desc": "Elevate every milestone with regal decor and premium service.",
    "occasion_anniversary_desc": "Curated romance with intimate touches and champagne delights.",
    "occasion_proposal_desc": "A private setting designed for unforgettable moments.",
    "occasion_baby_shower_desc": "Gentle luxury with pastel styling and thoughtful details.",
    "occasion_corporate_desc": "Executive event spaces with premium AV and hospitality.",
    "occasion_other_desc": "Bespoke styling for any exclusive experience.",
    "addon_premium_catering": "Premium Catering",
    "addon_premium_catering_desc": "Curated gourmet menu with premium drinks.",
    "addon_flower_arrangement": "Floral Styling",
    "addon_flower_arrangement_desc": "Bespoke floral installation and centerpiece design.",
    "addon_live_music": "Live Music",
    "addon_live_music_desc": "Piano, violin or acoustic ensemble for atmosphere.",
    "whyReviewMatters": "Why Your Review Matters",
    "helpServeBetter": "Help us serve better",
    "choosePerfectSuite": "Helps future guests choose the perfect suite",
    "motivateTeam": "Motivates our team to maintain luxury standards",
    "shapeImprovements": "Your insights directly shape service improvements",
    "verifiedReviews": "Verified reviews build trust in our community",
    "moderatedQuality": "Reviews are moderated for quality. Only your first name is shown publicly.",
    "ratingPreview": "Rating Preview",
    "noWrittenReview": "No written review yet...",
    "rateYourStay": "Rate Your Stay",
    "overallLabels_1": "Poor",
    "overallLabels_2": "Average",
    "overallLabels_3": "Good",
    "overallLabels_4": "Very Good",
    "overallLabels_5": "Excellent",
    "required": "Required",
    "charsLimit": "Be specific and honest — your feedback matters.",
    "ratingRequiredError": "Please rate your overall experience before submitting.",
    "reviewPlaceholder": "Share details about your experience — the ambience, service, what stood out, and anything that could be improved...",
    "welcome_back_name": "Guest",
    "ambience": "Ambience",
    "cleanliness": "Cleanliness",
    "service": "Service",
    "decoration": "Decoration",
    "valueForMoney": "Value for Money"
  },
  "admin": {
    "dashboard": "Dashboard",
    "bookings": "Bookings",
    "suiteBooking": "Suite Booking",
    "suites": "Suites",
    "addonManagement": "Add-on Management",
    "celebrationMembership": "Celebration Membership",
    "userManagement": "User Management",
    "analytics": "Analytics",
    "offersRefund": "Offers & Coupon Configurations",
    "ratingsReviews": "Ratings & Reviews",
    "settings": "Settings",
    "logout": "Logout",
    "confirmLogout": "Confirm Logout",
    "confirmLogoutText": "Are you sure you want to logout?",
    "yesLogout": "Yes, Logout",
    "cancel": "Cancel",
    "search": "Search...",
    "revenue": "Revenue",
    "avgBookingValue": "Avg. Booking Value",
    "adminUser": "Admin User",
    "profile": "Profile",
    "adminPanel": "Admin Panel"
  }
};

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function translateText(text, targetLang) {
  // Safe delay between requests
  await delay(150);

  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${targetLang}&dt=t&q=${encodeURIComponent(text)}`;
  try {
    const res = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      }
    });
    const json = await res.json();
    return json[0].map(item => item[0]).join("");
  } catch (err) {
    console.error(`Error translating text "${text}" to ${targetLang}:`, err);
    return text; // fallback to English
  }
}

async function translateObject(obj, targetLang, existingObj = {}) {
  const result = {};
  for (const key of Object.keys(obj)) {
    if (typeof obj[key] === "object") {
      result[key] = await translateObject(obj[key], targetLang, existingObj ? existingObj[key] : {});
    } else {
      if (existingObj && existingObj[key]) {
        result[key] = existingObj[key];
      } else {
        result[key] = await translateText(obj[key], targetLang);
      }
    }
  }
  return result;
}

async function main() {
  const localesDir = path.join(__dirname, "locales");

  // 1. Write English directly
  const enPath = path.join(localesDir, "en.json");
  const enData = JSON.parse(fs.readFileSync(enPath, "utf8"));
  enData.app = newStrings;
  fs.writeFileSync(enPath, JSON.stringify(enData, null, 2), "utf8");
  console.log("English locales updated successfully.");

  // 2. Translate and write others
  for (const lang of LANGUAGES) {
    console.log(`Translating keys to: ${lang}...`);
    const langPath = path.join(localesDir, `${lang}.json`);
    let existingApp = {};
    if (fs.existsSync(langPath)) {
      const langData = JSON.parse(fs.readFileSync(langPath, "utf8"));
      existingApp = langData.app || {};
    }
    const translatedApp = await translateObject(newStrings, lang, existingApp);
    if (fs.existsSync(langPath)) {
      const langData = JSON.parse(fs.readFileSync(langPath, "utf8"));
      langData.app = translatedApp;
      fs.writeFileSync(langPath, JSON.stringify(langData, null, 2), "utf8");
      console.log(`Locales for ${lang} updated successfully.`);
    } else {
      console.warn(`Locale file not found for: ${lang}`);
    }
  }
  console.log("All locales translated and saved successfully!");
}

main().catch(err => {
  console.error("Translation script failed:", err);
});
